# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

CONFIG_ZMK_USB_LOGGING=n

# base
CONFIG_ZMK_USB=y
CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=5
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SLEEP=n
CONFIG_BT_BAS=y

# display
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
# specific display
CONFIG_I2C=y
# CONFIG_SSD1306=y
